--
-- V1 - the schema as ddl-auto left it.
--
-- ==========================================================================
-- THIS FILE IS A PHOTOGRAPH, NOT A DESIGN
-- ==========================================================================
-- Captured with pg_dump from a running gatepassdb that Hibernate's ddl-auto=update
-- had built up over the project. It exists so a FRESH database can be created
-- from migrations rather than from whatever Hibernate decides to emit on the
-- day - which is how two schema faults got in already:
--
--   * verification_status was never created at all. ddl-auto issued
--     "alter table ... add column ... not null" against a table that already
--     had rows, Postgres refused it, and Hibernate logged that as a WARNING.
--     The service started healthy and every read failed.
--
--   * host_user_id could not be dropped, because ddl-auto only ever adds.
--     Every new visitor request 500'd until someone ran ALTER TABLE by hand.
--
-- ==========================================================================
-- EXISTING DATABASES DO NOT RUN THIS
-- ==========================================================================
-- spring.flyway.baseline-on-migrate marks a database that already has these
-- tables as being at version 1 without executing anything. Only an empty
-- database runs this file. Every change from here on is V2, V3, ... and runs
-- everywhere exactly once.
--

--
-- Name: bulk_upload_batches; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.bulk_upload_batches (
    id bigint NOT NULL,
    campus_id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    error_report_key character varying(300),
    event_id bigint,
    failure_message character varying(500),
    invalid_rows integer NOT NULL,
    object_key character varying(300) NOT NULL,
    original_filename character varying(260),
    pass_type character varying(20) NOT NULL,
    processed_rows integer NOT NULL,
    status character varying(20) NOT NULL,
    total_rows integer NOT NULL,
    updated_at timestamp(6) without time zone,
    uploaded_by bigint NOT NULL,
    valid_rows integer NOT NULL,
    CONSTRAINT bulk_upload_batches_invalid_rows_check CHECK ((invalid_rows >= 0)),
    CONSTRAINT bulk_upload_batches_pass_type_check CHECK (((pass_type)::text = ANY ((ARRAY['DAILY'::character varying, 'EVENT'::character varying])::text[]))),
    CONSTRAINT bulk_upload_batches_processed_rows_check CHECK ((processed_rows >= 0)),
    CONSTRAINT bulk_upload_batches_status_check CHECK (((status)::text = ANY ((ARRAY['VALIDATING'::character varying, 'VALIDATED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT bulk_upload_batches_total_rows_check CHECK ((total_rows >= 0)),
    CONSTRAINT bulk_upload_batches_valid_rows_check CHECK ((valid_rows >= 0))
);

-- Name: bulk_upload_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.bulk_upload_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bulk_upload_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: events; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.events (
    id bigint NOT NULL,
    campus_id bigint NOT NULL,
    is_cancelled boolean NOT NULL,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    description character varying(1000),
    name character varying(180) NOT NULL,
    updated_at timestamp(6) without time zone,
    valid_from date NOT NULL,
    valid_to date NOT NULL
);

-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: gate_passes; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.gate_passes (
    id bigint NOT NULL,
    batch_id bigint,
    campus_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint,
    holder_name character varying(120) NOT NULL,
    holder_user_id bigint NOT NULL,
    pass_type character varying(20) NOT NULL,
    paused_reason character varying(500),
    pdf_key character varying(300),
    qr_key character varying(300),
    revoked_at timestamp(6) without time zone,
    revoked_by bigint,
    revoked_reason character varying(500),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    valid_from date NOT NULL,
    valid_to date,
    visitor_request_id bigint,
    CONSTRAINT gate_passes_pass_type_check CHECK (((pass_type)::text = ANY ((ARRAY['DAILY'::character varying, 'EVENT'::character varying])::text[]))),
    CONSTRAINT gate_passes_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'PAUSED'::character varying, 'EXPIRED'::character varying, 'REVOKED'::character varying])::text[])))
);

-- Name: gate_passes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.gate_passes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gate_passes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: visitor_requests; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.visitor_requests (
    id bigint NOT NULL,
    campus_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint,
    host_user_id bigint,
    otp_verified boolean NOT NULL,
    purpose character varying(500) NOT NULL,
    reject_reason character varying(500),
    reviewed_at timestamp(6) without time zone,
    reviewed_by bigint,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    visit_from date NOT NULL,
    visit_to date NOT NULL,
    visitor_email character varying(180) NOT NULL,
    visitor_name character varying(120) NOT NULL,
    visitor_phone character varying(20),
    visitor_user_id bigint,
    date_of_birth date,
    gender character varying(20),
    id_number character varying(40),
    id_proof_key character varying(300),
    id_type character varying(20),
    photo_key character varying(300),
    purpose_type character varying(20) NOT NULL,
    visitor_type character varying(20) NOT NULL,
    CONSTRAINT visitor_requests_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying, 'PREFER_NOT_TO_SAY'::character varying])::text[]))),
    CONSTRAINT visitor_requests_id_type_check CHECK (((id_type)::text = ANY ((ARRAY['AADHAAR'::character varying, 'PAN'::character varying, 'PASSPORT'::character varying, 'VOTER_ID'::character varying])::text[]))),
    CONSTRAINT visitor_requests_purpose_type_check CHECK (((purpose_type)::text = ANY ((ARRAY['MEETING'::character varying, 'INTERVIEW'::character varying, 'DELIVERY'::character varying, 'MAINTENANCE'::character varying, 'EVENT'::character varying, 'ACADEMIC'::character varying, 'PERSONAL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT visitor_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT visitor_requests_visitor_type_check CHECK (((visitor_type)::text = ANY ((ARRAY['GUEST'::character varying, 'PARENT'::character varying, 'VENDOR'::character varying, 'CONTRACTOR'::character varying, 'ALUMNI'::character varying, 'CANDIDATE'::character varying, 'OTHER'::character varying])::text[])))
);

-- Name: visitor_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.visitor_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visitor_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: bulk_upload_batches bulk_upload_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.bulk_upload_batches
    ADD CONSTRAINT bulk_upload_batches_pkey PRIMARY KEY (id);

-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

-- Name: gate_passes gate_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.gate_passes
    ADD CONSTRAINT gate_passes_pkey PRIMARY KEY (id);

-- Name: visitor_requests visitor_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.visitor_requests
    ADD CONSTRAINT visitor_requests_pkey PRIMARY KEY (id);

-- Name: idx_bub_campus_status; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_bub_campus_status ON public.bulk_upload_batches USING btree (campus_id, status);

-- Name: idx_bub_event; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_bub_event ON public.bulk_upload_batches USING btree (event_id);

-- Name: idx_bub_uploaded_by; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_bub_uploaded_by ON public.bulk_upload_batches USING btree (uploaded_by);

-- Name: idx_ev_campus_dates; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_ev_campus_dates ON public.events USING btree (campus_id, valid_from, valid_to);

-- Name: idx_ev_created_by; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_ev_created_by ON public.events USING btree (created_by);

-- Name: idx_gp_batch; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_gp_batch ON public.gate_passes USING btree (batch_id);

-- Name: idx_gp_campus_status; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_gp_campus_status ON public.gate_passes USING btree (campus_id, status);

-- Name: idx_gp_event; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_gp_event ON public.gate_passes USING btree (event_id);

-- Name: idx_gp_expiry_sweep; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_gp_expiry_sweep ON public.gate_passes USING btree (status, valid_to);

-- Name: idx_gp_holder_status; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_gp_holder_status ON public.gate_passes USING btree (holder_user_id, status);

-- Name: idx_vr_campus_status; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_vr_campus_status ON public.visitor_requests USING btree (campus_id, status);

-- Name: idx_vr_email; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_vr_email ON public.visitor_requests USING btree (visitor_email);

-- Name: idx_vr_host; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_vr_host ON public.visitor_requests USING btree (host_user_id);
