spring.application.name=gatepass-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/gatepassdb
spring.datasource.username=perimity
spring.datasource.password=change_me_local_only

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html