package com.perimity.gatepass.validation;

import static org.assertj.core.api.Assertions.assertThat;

import com.perimity.gatepass.entity.enums.IdType;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * One valid and several invalid cases per document.
 *
 * The invalid ones are the point. Every string below has the RIGHT SHAPE and is
 * still wrong - a rule that only rejects obvious rubbish is not doing any work.
 */
class IdDocumentValidatorTest {

    /** Verhoeff-valid, generated by the checksum itself. Not a real person's. */
    private static final String VALID_AADHAAR = "234123412346";

    @Nested
    class Aadhaar {

        @Test
        void acceptsATwelveDigitNumberWithAValidChecksum() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, VALID_AADHAAR)).isTrue();
        }

        /**
         * The checksum's whole purpose. This differs from a valid number by one
         * digit, which is the commonest way to mistype one off a card.
         */
        @Test
        void rejectsASingleDigitError() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, "234123412345")).isFalse();
        }

        /** The other mistake people make: swapping two adjacent digits. */
        @Test
        void rejectsATransposition() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, "234123412364")).isFalse();
        }

        @Test
        void rejectsTwelveIdenticalDigits() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, "111111111111")).isFalse();
        }

        @Test
        void rejectsTheWrongLength() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, "23412341234")).isFalse();
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, "2341234123467")).isFalse();
        }

        @Test
        void rejectsLetters() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, "23412341234A")).isFalse();
        }
    }

    @Nested
    class Pan {

        @Test
        void acceptsFiveLettersFourDigitsALetter() {
            assertThat(IdDocumentValidator.isValid(IdType.PAN, "ABCDE1234F")).isTrue();
        }

        @Test
        void rejectsAMissingTrailingLetter() {
            assertThat(IdDocumentValidator.isValid(IdType.PAN, "ABCDE12345")).isFalse();
        }

        @Test
        void rejectsDigitsInTheLetterBlock() {
            assertThat(IdDocumentValidator.isValid(IdType.PAN, "ABC1E1234F")).isFalse();
        }

        /** Uppercased before matching, so a lowercase entry is accepted. */
        @Test
        void acceptsLowercaseByNormalising() {
            assertThat(IdDocumentValidator.isValid(IdType.PAN, "abcde1234f")).isTrue();
        }
    }

    @Nested
    class Passport {

        @Test
        void acceptsALetterAndSevenDigits() {
            assertThat(IdDocumentValidator.isValid(IdType.PASSPORT, "A1234567")).isTrue();
        }

        @Test
        void rejectsSixDigits() {
            assertThat(IdDocumentValidator.isValid(IdType.PASSPORT, "A123456")).isFalse();
        }

        @Test
        void rejectsTwoLeadingLetters() {
            assertThat(IdDocumentValidator.isValid(IdType.PASSPORT, "AB123456")).isFalse();
        }
    }

    @Nested
    class VoterId {

        @Test
        void acceptsThreeLettersAndSevenDigits() {
            assertThat(IdDocumentValidator.isValid(IdType.VOTER_ID, "ABC1234567")).isTrue();
        }

        @Test
        void rejectsTwoLeadingLetters() {
            assertThat(IdDocumentValidator.isValid(IdType.VOTER_ID, "AB12345678")).isFalse();
        }

        @Test
        void rejectsSixDigits() {
            assertThat(IdDocumentValidator.isValid(IdType.VOTER_ID, "ABC123456")).isFalse();
        }
    }

    @Nested
    class CrossType {

        /**
         * The reason this is not a field-level @Pattern: the same string is a
         * perfectly good PAN and not a passport.
         */
        @Test
        void aPanIsNotAPassport() {
            assertThat(IdDocumentValidator.isValid(IdType.PAN, "ABCDE1234F")).isTrue();
            assertThat(IdDocumentValidator.isValid(IdType.PASSPORT, "ABCDE1234F")).isFalse();
        }

        @Test
        void anAadhaarIsNotAVoterId() {
            assertThat(IdDocumentValidator.isValid(IdType.AADHAAR, VALID_AADHAAR)).isTrue();
            assertThat(IdDocumentValidator.isValid(IdType.VOTER_ID, VALID_AADHAAR)).isFalse();
        }
    }

    /** Optional field: absence is not invalidity. The pairing rule handles that. */
    @Nested
    class Absence {

        @Test
        void treatsNullAndBlankAsNothingToCheck() {
            assertThat(IdDocumentValidator.isValid(IdType.PAN, null)).isTrue();
            assertThat(IdDocumentValidator.isValid(IdType.PAN, "   ")).isTrue();
            assertThat(IdDocumentValidator.isValid(null, "ABCDE1234F")).isTrue();
        }
    }
}
