import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, FileDropzone, FormField, ProgressBar, ErrorState } from '../shared/ui';
import { gatepass, useApi } from '../api';

/**
 * Screen 1 of 3 — pick a sheet, validate it. LIVE against gatepass-service.
 *
 * Validation is a separate step from confirmation on purpose, and that is a
 * product decision, not a technical one: issuing 580 passes is irreversible
 * and emails 580 people. Nobody should be one click away from it.
 *
 * The template link is generated by the backend rather than checked into the
 * repo, so its columns cannot drift from what the parser actually reads.
 */
export default function BulkUpload() {
  const nav = useNavigate();
  const [file, setFile] = useState(null);
  const [passType, setPassType] = useState('EVENT');
  const [eventId, setEventId] = useState('');
  const [pct, setPct] = useState(null);
  const [error, setError] = useState(null);

  // Only EVENT batches need an event, so only fetch the list when one is needed.
  const { data: events } = useApi(() => gatepass.events({ size: 100 }), [], { skip: passType !== 'EVENT' });
  const eventOptions = (events?.content ?? []).filter((e) => !e.cancelled);

  const ready = file && passType && (passType !== 'EVENT' || eventId);

  const submit = async () => {
    setError(null);
    setPct(0);
    try {
      const batch = await gatepass.validateSheet(file, passType, eventId || null,
        (e) => e.total && setPct(Math.round((e.loaded * 100) / e.total)));
      nav(`/bulk/${batch.id}/review`);
    } catch (e) {
      setError(e);
      setPct(null);
    }
  };

  return (
    <div className="p-stack" style={{ maxWidth: 640 }}>
      <div>
        <h1 className="p-h1">Bulk upload</h1>
        <p className="p-caption">
          Upload a sheet of attendees. Nothing is issued until you confirm on the
          next screen.
        </p>
      </div>

      <div className="p-card p-pad">
        <div className="p-stack">
          <FormField
            label="Pass type" as="select" required value={passType}
            onChange={(e) => { setPassType(e.target.value); setEventId(''); }}
            options={['EVENT', 'STUDENT']}
            help="EVENT issues passes for one event. STUDENT issues rolling daily passes."
          />

          {passType === 'EVENT' && (
            <FormField
              label="Event" as="select" required value={eventId}
              onChange={(e) => setEventId(e.target.value)}
              options={['', ...eventOptions.map((e) => `${e.id} — ${e.name}`)]}
              help={eventOptions.length ? undefined : 'No events yet. Create one first.'}
            />
          )}

          <div>
            <span className="p-field__label">Attendee sheet</span>
            <FileDropzone
              accept=".xlsx,.xls,.csv"
              maxMb={10}
              file={file}
              onFile={setFile}
              hint="XLSX or CSV. One attendee per row."
            />
            <p className="p-field__help">
              <a href={gatepass.templateUrl(passType)}>Download the {passType.toLowerCase()} template</a>
              {' '}— it is generated from the parser, so the columns are always current.
            </p>
          </div>

          {pct !== null && (
            <div>
              <ProgressBar value={pct} max={100} label={pct < 100 ? 'Uploading' : 'Validating rows…'} />
              {pct === 100 && (
                <p className="p-caption">
                  A 600-row sheet takes a few seconds. This screen is waiting on
                  the row-by-row check, not on the network.
                </p>
              )}
            </div>
          )}

          {error && <ErrorState title="Upload failed" message={error.message} onRetry={submit} />}

          <Button onClick={submit} disabled={!ready} loading={pct !== null && !error}>
            Validate sheet
          </Button>
        </div>
      </div>

      <p className="p-caption">
        Rows on the campus blocklist are counted as errors and appear in the
        report without a reason. That is deliberate — see the error report note
        on the next screen.
      </p>
    </div>
  );
}
