--
-- V1 - the schema as ddl-auto left it.
--
-- ==========================================================================
-- THIS FILE IS A PHOTOGRAPH, NOT A DESIGN
-- ==========================================================================
-- Captured with pg_dump from a running userdb that Hibernate's ddl-auto=update
-- had built up over the project. It exists so a FRESH database can be created
-- from migrations rather than from whatever Hibernate decides to emit on the
-- day - which is how two schema faults got in already:
--
--   * verification_status was never created at all. ddl-auto issued
--     "alter table ... add column ... not null" against a table that already
--     had rows, Postgres refused it, and Hibernate logged that as a WARNING.
--     The service started healthy and every read failed.
--
--   * host_user_id could not be dropped, because ddl-auto only ever adds.
--     Every new visitor request 500'd until someone ran ALTER TABLE by hand.
--
-- ==========================================================================
-- EXISTING DATABASES DO NOT RUN THIS
-- ==========================================================================
-- spring.flyway.baseline-on-migrate marks a database that already has these
-- tables as being at version 1 without executing anything. Only an empty
-- database runs this file. Every change from here on is V2, V3, ... and runs
-- everywhere exactly once.
--

--
-- Name: campus_import_settings; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.campus_import_settings (
    id bigint NOT NULL,
    campus_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    form_url character varying(500),
    responses_sheet_id character varying(128),
    updated_at timestamp(6) without time zone,
    updated_by bigint
);

-- Name: campus_import_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.campus_import_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campus_import_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: departments; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.departments (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    campus_id bigint NOT NULL,
    code character varying(32) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone
);

-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: documents; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    doc_type character varying(20) NOT NULL,
    file_name character varying(255) NOT NULL,
    mime_type character varying(100),
    s3_key character varying(512) NOT NULL,
    user_id bigint NOT NULL,
    verification_remarks character varying(500),
    is_verified boolean NOT NULL,
    verified_at timestamp(6) without time zone,
    verified_by bigint,
    CONSTRAINT documents_doc_type_check CHECK (((doc_type)::text = ANY ((ARRAY['PHOTO'::character varying, 'ID_PROOF'::character varying, 'CERTIFICATE'::character varying, 'OTHER'::character varying])::text[])))
);

-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: faculty_profiles; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.faculty_profiles (
    id bigint NOT NULL,
    campus_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    department_id bigint,
    designation character varying(100),
    employee_id character varying(32),
    photo_s3_key character varying(512),
    qualification character varying(150),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

-- Name: faculty_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.faculty_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: student_import_batches; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.student_import_batches (
    id bigint NOT NULL,
    campus_id bigint NOT NULL,
    confirmed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    created_count integer NOT NULL,
    failure_reason character varying(500),
    filename character varying(255),
    finished_at timestamp(6) without time zone,
    missing_photo_count integer NOT NULL,
    rejected_count integer NOT NULL,
    status character varying(20) NOT NULL,
    total_rows integer NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_count integer NOT NULL,
    uploaded_by bigint NOT NULL,
    valid_rows integer NOT NULL,
    CONSTRAINT student_import_batches_status_check CHECK (((status)::text = ANY ((ARRAY['VALIDATING'::character varying, 'VALIDATED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);

-- Name: student_import_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.student_import_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_import_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: student_import_rows; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.student_import_rows (
    id bigint NOT NULL,
    address character varying(250),
    batch_id bigint NOT NULL,
    date_of_birth date,
    department_id bigint,
    department_label character varying(150),
    email character varying(180),
    first_name character varying(60),
    full_name character varying(120),
    gender character varying(20),
    last_name character varying(60),
    message character varying(500),
    middle_name character varying(60),
    outcome character varying(20) NOT NULL,
    phone_country_code character varying(5),
    phone_number character varying(15),
    photo_drive_id character varying(128),
    roll_no character varying(32),
    row_number integer NOT NULL,
    user_id bigint,
    CONSTRAINT student_import_rows_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying, 'PREFER_NOT_TO_SAY'::character varying])::text[]))),
    CONSTRAINT student_import_rows_outcome_check CHECK (((outcome)::text = ANY ((ARRAY['PENDING'::character varying, 'CREATED'::character varying, 'UPDATED'::character varying, 'REJECTED'::character varying])::text[])))
);

-- Name: student_import_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.student_import_rows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_import_rows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: student_profiles; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.student_profiles (
    id bigint NOT NULL,
    address character varying(250),
    campus_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    department_id bigint,
    gov_id character varying(12),
    photo_s3_key character varying(512),
    roll_no character varying(32),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    alt_phone_country_code character varying(5),
    alt_phone_number character varying(15),
    date_of_birth date,
    first_name character varying(60),
    gender character varying(20),
    last_name character varying(60),
    middle_name character varying(60),
    phone_country_code character varying(5),
    phone_number character varying(15),
    submitted_at timestamp(6) without time zone,
    verification_remarks character varying(500),
    verified_at timestamp(6) without time zone,
    verified_by bigint,
    verification_status character varying(20) NOT NULL,
    CONSTRAINT student_profiles_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying, 'PREFER_NOT_TO_SAY'::character varying])::text[]))),
    CONSTRAINT student_profiles_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);

-- Name: student_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.student_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: campus_import_settings campus_import_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.campus_import_settings
    ADD CONSTRAINT campus_import_settings_pkey PRIMARY KEY (id);

-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);

-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

-- Name: faculty_profiles faculty_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.faculty_profiles
    ADD CONSTRAINT faculty_profiles_pkey PRIMARY KEY (id);

-- Name: student_import_batches student_import_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.student_import_batches
    ADD CONSTRAINT student_import_batches_pkey PRIMARY KEY (id);

-- Name: student_import_rows student_import_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.student_import_rows
    ADD CONSTRAINT student_import_rows_pkey PRIMARY KEY (id);

-- Name: student_profiles student_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_pkey PRIMARY KEY (id);

-- Name: departments uk_departments_campus_code; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.departments
    ADD CONSTRAINT uk_departments_campus_code UNIQUE (campus_id, code);

-- Name: faculty_profiles uk_faculty_campus_emp; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.faculty_profiles
    ADD CONSTRAINT uk_faculty_campus_emp UNIQUE (campus_id, employee_id);

-- Name: faculty_profiles uk_faculty_user; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.faculty_profiles
    ADD CONSTRAINT uk_faculty_user UNIQUE (user_id);

-- Name: campus_import_settings uk_import_settings_campus; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.campus_import_settings
    ADD CONSTRAINT uk_import_settings_campus UNIQUE (campus_id);

-- Name: student_profiles uk_student_campus_roll; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT uk_student_campus_roll UNIQUE (campus_id, roll_no);

-- Name: student_profiles uk_student_user; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT uk_student_user UNIQUE (user_id);

-- Name: idx_departments_campus; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_departments_campus ON public.departments USING btree (campus_id);

-- Name: idx_documents_type; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_documents_type ON public.documents USING btree (user_id, doc_type);

-- Name: idx_documents_user; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_documents_user ON public.documents USING btree (user_id);

-- Name: idx_faculty_campus; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_faculty_campus ON public.faculty_profiles USING btree (campus_id);

-- Name: idx_faculty_department; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_faculty_department ON public.faculty_profiles USING btree (department_id);

-- Name: idx_import_batch_campus; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_import_batch_campus ON public.student_import_batches USING btree (campus_id);

-- Name: idx_import_batch_uploader; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_import_batch_uploader ON public.student_import_batches USING btree (uploaded_by);

-- Name: idx_import_row_batch; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_import_row_batch ON public.student_import_rows USING btree (batch_id);

-- Name: idx_import_row_email; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_import_row_email ON public.student_import_rows USING btree (email);

-- Name: idx_student_campus; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_student_campus ON public.student_profiles USING btree (campus_id);

-- Name: idx_student_department; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX idx_student_department ON public.student_profiles USING btree (department_id);
