package com.perimity.qr;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/*
 * DAY 8 CHANGE: auto-startup disabled for the listener container.
 *
 * Without this line, running ./mvnw test starts a real consumer against
 * whatever broker application.properties points at - so the test run quietly
 * eats messages off the development qr.generate.request queue, and passes issued
 * while the build was running get generated by a JVM that then exits. Nothing
 * fails; work just disappears.
 *
 * The context still wires the listener, the converter and the topology beans,
 * so this test still proves they are all constructible. It only declines to
 * begin consuming.
 */
@SpringBootTest(properties = "spring.rabbitmq.listener.simple.auto-startup=false")
class QrServiceApplicationTests {

	@Test
	void contextLoads() {
	}

}
