package com.perimity.user.storage;

import java.io.InputStream;
import java.time.Duration;

/**
 * Object storage, behind an interface.
 *
 * Copied from campus-service, which its own comment names as the reference
 * implementation for the other five services. Only the package line and the
 * local-serve path differ, so all six behave identically and one person can
 * debug any of them.
 *
 * Two implementations, chosen by one property:
 *
 *   perimity.storage.type=local   a folder on disk. The DEFAULT.
 *   perimity.storage.type=s3      the real thing.
 *
 * Local is the default on purpose. Nobody should need an AWS account, a
 * credential file or a network connection to run this project, and a teammate
 * who cannot start the service is a teammate who cannot work. On Day 22 one
 * property flips and nothing else changes.
 *
 * It also keeps the demo safe: if AWS is unreachable on presentation day, the
 * whole system still runs from a laptop.
 */
public interface StorageService {

    /**
     * @param key         full object key, generated by StorageKeys - never a
     *                    path supplied by a client
     * @param contentType the REAL type, verified by the caller against the
     *                    file's leading bytes - never the one the browser claimed
     */
    StoredObject put(String key, InputStream content, long sizeBytes, String contentType);

    /** Short-lived read URL. Never hand out a permanent public link. */
    String presignedReadUrl(String key, Duration validFor);

    boolean exists(String key);

    /**
     * Deletes an object. Used when a photo is replaced, so the old file does not
     * sit in the bucket forever costing money and holding a picture of someone
     * who has since asked for it to be changed.
     */
    void delete(String key);
}
