package com.perimity.auth.dto.request;

import com.perimity.auth.validation.ValidationPatterns;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Body of POST /api/internal/auth/users/students - user-service asking for a
 * batch of STUDENT accounts during a bulk import.
 *
 * ==========================================================================
 * WHY THIS IS NOT THE EXISTING /batch ENDPOINT
 * ==========================================================================
 * That one creates lightweight VISITOR identities: no password, OTP only, the
 * weakest account this system has. It was built for the visitor spreadsheet
 * upload and it is correct for that.
 *
 * A student is a different thing - it holds a password, it can sign in, and it
 * gets a campus pass. The tempting shortcut was to add a `role` field to the
 * visitor endpoint and reuse everything. That was rejected deliberately: the
 * internal API key is shared across all six services, so an endpoint that
 * accepts a role means a leaked key can mint a CAMPUS_ADMIN. An endpoint that
 * only ever produces students means a leaked key can only ever produce
 * students, which is a far smaller thing to be wrong about.
 *
 * ==========================================================================
 * THERE IS DELIBERATELY NO ROLE FIELD
 * ==========================================================================
 * Not "a role field that is validated". Not "a role field the server ignores".
 * None. A field that is ignored is a field somebody eventually trusts - the
 * exact mistake DocumentVerificationDto made with verifiedBy, where a comment
 * telling the service to ignore it was the only thing keeping it honest.
 *
 * The role is STUDENT because of which endpoint this is.
 */
@Schema(description = "Create or resolve STUDENT accounts for a bulk import")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InternalStudentBatchDto {

    /**
     * The campus every account in this batch belongs to.
     *
     * On the batch, not the row. One upload is one campus - a sheet mixing
     * campuses is a mistake, and letting each row name its own would make that
     * mistake succeed quietly.
     */
    @NotNull(message = "Campus is required")
    @Positive
    @Schema(example = "2")
    private Long campusId;

    /**
     * The faculty or admin who uploaded the sheet.
     *
     * Recorded as the actor on every audit entry this batch writes, so "who
     * created account 481" has an answer that is a person. Without it the audit
     * trail would say a service did it, which is true and useless.
     */
    @NotNull(message = "The uploading account is required")
    @Positive
    @Schema(example = "6")
    private Long uploadedBy;

    @NotEmpty(message = "A batch must have at least one row")
    @Valid
    private List<Row> rows;

    /** For the audit note - which import this came from. */
    @Size(max = 100)
    @Schema(example = "student-import-batch-14")
    private String source;

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Row {

        /**
         * The row's position in the uploaded sheet, so a failure can be
         * reported against the line the person can actually see.
         */
        @NotNull
        @Schema(example = "47")
        private Integer rowNumber;

        @NotBlank(message = "Email is required")
        @Pattern(regexp = ValidationPatterns.EMAIL, message = ValidationPatterns.EMAIL_MESSAGE)
        @Size(max = 180)
        private String email;

        @NotBlank(message = "Name is required")
        @Size(max = 120)
        @Pattern(regexp = ValidationPatterns.PERSON_NAME,
                 message = ValidationPatterns.PERSON_NAME_MESSAGE)
        private String name;

        @Pattern(regexp = "^$|" + ValidationPatterns.PHONE,
                 message = ValidationPatterns.PHONE_MESSAGE)
        @Size(max = 20)
        private String phone;

        /**
         * The temporary password for this account.
         *
         * Generated by the CALLER, one per row, never a shared value - a batch
         * where every student got the same password would mean any of them
         * could sign in as any other until the first login change, and some
         * would never change it.
         *
         * mustChangePassword is set on every account this endpoint creates, so
         * the value here is good for exactly one sign-in.
         */
        @NotBlank(message = "A temporary password is required")
        @Size(min = 8, max = 72)
        private String temporaryPassword;
    }
}
