package com.perimity.user.client;

import java.util.List;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

/**
 * Declarative call into auth-service, for bulk student onboarding.
 *
 * ==========================================================================
 * WHY user-service CREATES ACCOUNTS AT ALL
 * ==========================================================================
 * It does not. It asks auth-service to, which is the only service allowed to
 * write a users row. The import runs here because it owns student profiles and
 * the verification state machine, but the account half of each row has to go
 * through the service that owns accounts.
 *
 * ==========================================================================
 * WHY THIS IS NOT THE FACULTY'S JWT
 * ==========================================================================
 * The tempting alternative was to forward the uploading faculty's token, so
 * accounts would be created under their own authority and auth-service's
 * existing role rules would apply unchanged. It reads better and it does not
 * work: the import is a background job over hundreds of rows with Drive
 * fetches, passes and emails in it, and a JWT expires long before that
 * finishes. Rows would start failing partway through a batch, apparently at
 * random.
 *
 * So the internal key, and a dedicated endpoint that can only ever produce a
 * STUDENT. uploadedBy carries the faculty member's id so the audit trail still
 * names a person rather than a service.
 *
 * The contextId matters: two @FeignClient interfaces without distinct ones
 * collide at startup with a bean name clash that reads as a mystery.
 */
@FeignClient(
        name = "auth-service",
        contextId = "userStudentImport",
        url = "${perimity.services.auth-url:}",
        configuration = FeignSupportConfig.class)
public interface AuthFeignClient {

    @PostMapping("/api/internal/auth/users/students")
    StudentBatchEnvelope createStudents(@RequestBody StudentBatchRequest request);

    /**
     * Mirrors InternalStudentBatchDto in auth-service. A copy, like every other
     * cross-service contract here - Jackson matches by field NAME, so keep the
     * names identical and change both in one commit.
     *
     * There is no role field. The endpoint decides, and a field that is ignored
     * is a field somebody eventually trusts.
     */
    record StudentBatchRequest(
            Long campusId,
            Long uploadedBy,
            String source,
            List<Row> rows) {

        public record Row(
                Integer rowNumber,
                String email,
                String name,
                String phone,
                /**
                 * One per row, generated by the caller. A batch sharing a
                 * password would let any student in it sign in as any other
                 * until the first one changed theirs.
                 */
                String temporaryPassword) { }
    }

    record StudentBatchEnvelope(boolean success, String message, StudentBatchResult data) { }

    record StudentBatchResult(
            int totalRows,
            int reusedCount,
            int createdCount,
            int refusedCount,
            int duplicateCount,
            List<RowResult> results) { }

    /**
     * outcome is REUSED, CREATED, REFUSED or DUPLICATE.
     *
     * A String rather than an enum on purpose: auth-service adding an outcome
     * this service has never heard of should not make the whole batch
     * unparseable. An unknown value can be reported against the row; a
     * deserialisation failure loses every row in the response.
     */
    record RowResult(Integer rowNumber, String email, String outcome, Long userId) { }
}
